### ISSUE TITLE
请问about页面和背景上面的子怎么修改呢？

### ISSUE THREAD

**Issue by Military-axe** [iGuan7u/Acetolog#11]
非常中意这个主题，作者tql，但是配置我遇到一些问题。
我的about没出来就很难受
还有就是背景版的字体不知道在哪里修改，希望您能帮助我
![image](https://user-images.githubusercontent.com/49434905/94574842-2a27a500-02a6-11eb-86d1-2befe95b8448.png)
![image](https://user-images.githubusercontent.com/49434905/94578186-00707d00-02aa-11eb-9d02-804d8de2de98.png)

**Comment by liusicun** [comment]
在index.swig 中 

`{% block content %}
    <div class="al_index_background dis_flex_center al_full_cover">
        <div class="al_pos_ab al_letter al_index_background_letter">
            {{ config.bio|default('************')|first|upper }}
        </div>
        <h2 class="al_index_background_bio">
            {{ config.bio|default('************') }}
        </h2>
    </div>`

**Comment by liusicun** [comment]
在index.swig

```
{% block content %}
    <div class="al_index_background dis_flex_center al_full_cover">
        <div class="al_pos_ab al_letter al_index_background_letter">
            {{ config.bio|default('**************')|first|upper }}
        </div>
        <h2 class="al_index_background_bio">
            {{ config.bio|default('**************') }}
        </h2>
    </div>
```

**Comment by iGuan7u** [comment]
感谢你的喜欢。
Acetolog 默认使用的是博客根目录的 `_config.yml` 中的 `bio` 字段，字体设置可以修改 index.swig 文件中的 `al_index_background_letter` 样式。
