### ISSUE TITLE
URL生成有毒啊

### ISSUE THREAD

**Issue by chenbuyi2019** [iGuan7u/Acetolog#16]
我导入了我以前的文章，我发现　page/2 还是正常的。    
再点击一下下一页，直接　page/2/page/3 真NB。     
然后第二页里面的链接全部都是　/page/2 开头的。   
你自己都不测试的嘛（

**Comment by iGuan7u** [comment]
@gordonwalkedby 因为我自己的博客还没有写到第三页，而 hexo 的 unit test 也没有第三页的测试，所以没有发现这个问题
感谢你的反馈，修复已经提交到 master 分支中

**Comment by NeoSmithETH** [comment]
> 我导入了我以前的文章，我发现　page/2 还是正常的。
> 再点击一下下一页，直接　page/2/page/3 真NB。
> 然后第二页里面的链接全部都是　/page/2 开头的。
> 你自己都不测试的嘛（

哈哈哈，有不少人喜欢极简的主题风格，来一起做点儿贡献啊，把 tag 之类的页面也搞搞……

**Comment by iGuan7u** [comment]
> > 我导入了我以前的文章，我发现　page/2 还是正常的。
> > 再点击一下下一页，直接　page/2/page/3 真NB。
> > 然后第二页里面的链接全部都是　/page/2 开头的。
> > 你自己都不测试的嘛（
> 
> 哈哈哈，有不少人喜欢极简的主题风格，来一起做点儿贡献啊，把 tag 之类的页面也搞搞……

就喜欢这样的回复，更有建设性。上面的回复听起来就阴阳怪气的，哎。。
