### ISSUE TITLE
feat: 希望能从配置文件上修改一切，而不用改动主题源码，除了特定需求外。

### ISSUE THREAD

**Issue by lzm0x219** [iGuan7u/Acetolog#3]

**Comment by iGuan7u** [comment]
对于已经在 hexo 博客配置文件中已经存在的字段，我个人希望都能尽可能的复用
可是对于一些 Acetolog 特定的主题设置，我觉得还是放在 theme config 中比较合适，后面使用者如果希望切换别的主题，还是能直接迁移，无需再删改自己的博客配置。

**Comment by lzm0x219** [comment]
也有道理。

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=10.0.32&pv=10.15.3&source=email_footer_2]
On Thu, Feb 13, 2020 at 8:32 PM, iGuan7u <notifications@github.com> wrote:
对于已经在 hexo 博客配置文件中已经存在的字段，我个人希望都能尽可能的复用
可是对于一些 Acetolog 特定的主题设置，我觉得还是放在 theme config 中比较合适，后面使用者如果希望切换别的主题，还是能直接迁移，无需再删改自己的博客配置。
