### ISSUE TITLE
你好，我非常喜欢这主题，但是在构建的时候，碰到这个问题一直解决不了

### ISSUE THREAD

**Issue by mzfangy** [iGuan7u/Acetolog#9]
![image](https://user-images.githubusercontent.com/62063137/76477888-b1641700-6441-11ea-8cf8-153b0b6146f3.png)
![image](https://user-images.githubusercontent.com/62063137/76477907-bcb74280-6441-11ea-9a2e-f3ff4a114e0b.png)

盼望回复！

**Comment by mzfangy** [comment]
![image](https://user-images.githubusercontent.com/62063137/76477941-e2dce280-6441-11ea-9bc4-00dee5caaf09.png)

**Comment by iGuan7u** [comment]
你好，感谢你的赞赏。
报错信息似乎是 `hexo-wordcount` 这个依赖没有安装成功，`wordcount` 与 `min2read` 这两个方法都是由这个依赖提供的，请确认一下。

可以尝试把 node_modules 文件夹删掉重新安装依赖。

**Comment by iGuan7u** [comment]
留意到你的博客似乎正常运行了，这个 isuse 就此关闭。
